name: first

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@1
    - name: Run a one-line script
      run: echo Hello, World!
    - name: Run a multi-line script
      run: |
        echo foo
        echo bar
        

