name: first

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World!
    - name: Run a multi-line script
      run: |
        echo foo
        echo bar
  job2:
    runs-on: windows-latest
    needs: [job1]

    steps:
      - uses: actions/checkout@v1
      - name: Run simple script
        run: |
          echo 'Hello from windows'
        

