name: second

on: 
  push:
    branches:
      - challenge1

jobs:
  job1:
      name: linux
      runs-on: ubuntu-latest
      steps:
        - run: date

  job2:
      name: windows
      runs-on: windows-latest
      steps:
      - run: Get-Date
  job3:
      name: mac
      runs-on: macos-latest
      steps:

      - run: date
  job4:
      needs: [job1, job2, job3]
      name: any
      runs-on: ubuntu-latest
      steps: 

      - run: date

